### ISSUE TITLE
Weapon EFX identification (Switch axe, Charge Blade, shared effects)

### ISSUE THREAD

**Issue by MrNiggles** [mhvuze/MonsterHunterRiseModding#10]
Thanks to NSACloud for lending me his findings with the Switch Axe. I've used it to narrow down some of the effects to a move and its related moves to get the details. I've also identified most of the ones that he couldn't identify (except for the very first one, I have no idea what that is myself). Tested with all phial types (Power/Exhaust/Poison/Dragon/Element/Para),

=======================================
**Switch Axe**
[efd_S-axe]
efd_0004_s-axe_00_0000.efx = ??? EFX looks like ribbon efx, but can't find where it's used
efd_0004_s-axe_00_0001.efx = plays when you hit a WE zone (blue crit flash, training dummy head/belly). Note that it plays WITH the flash, which is a common effect shared with other weapons.
efd_0004_s-axe_10_0000.efx = Element discharge explosion (both CSD and ZSD types)
efd_0004_s-axe_10_0050.efx = advancing slash electricity (after soaring wyvern blade)
efd_0004_s-axe_10_0060.efx = advancing slash explosion (plays after 0050)
efd_0004_s-axe_20_0000.efx = extra hit effect during amped up state
efd_0004_s-axe_30_0000.efx = Axe/Sword mode morph sparks
efd_0004_s-axe_30_0001.efx = switch charger axe glow
efd_0004_s-axe_40_0000.efx = amped up state electricity (applies to both axe/sword modes)
efd_0004_s-axe_40_0001.efx = the smoke and distortion from element discharge (applies to grounded ED, ZSD, and end of Soaring WB > advancing slash)
efd_0004_s-axe_40_0002.efx = the smoke and distortion from compressed element discharge
efd_0004_s-axe_40_0003.efx = distortion effect during compressed element discharge
efd_0004_s-axe_40_0004.efx = he smoke and distortion from element discharge (at start of advancing slash after Soaring WB)
efd_0004_s-axe_40_0010.efx = sword mode electricity loop
efd_0004_s-axe_50_0000.efx = Heavy Slam Sparks (does not apply to invincible gambit slam or forward overhead slash)

The wirebug effects for switch charger/invincible gambit/soaring wyvern blade are common effects shared with other weapons, so they won't be found in efd_s-axe.

=======================================
**Charge Blade**
[efd_c-axe]
efd_0004_c-axe_00_0000.efx = ??? Same as Switch Axe
efd_0004_c-axe_00_0001.efx = ??? Same as Switch Axe
efd_0004_c-axe_10_0000.efx = shield smoke from ultra/amped element discharge and counter peak performance
efd_0004_c-axe_20_0000.efx = extra hit effect during charged state (similar to Switch Axe)
efd_0004_c-axe_20_0020.efx = extra hit effect during charged state, includes the impact effect at the end of condensed element slash (sword mode with charged shield)
efd_0004_c-axe_20_0030.efx = ultra element discharge projectiles
efd_0004_c-axe_30_0000.efx = beyblade spin effect on the shield during ultra element discharge and condensed spinning slash
efd_0004_c-axe_30_0001.efx = ???
efd_0004_c-axe_40_0000.efx = shield spark effects when reloading + shield thrust with charged shield
efd_0004_c-axe_40_0001.efx =  reload near end, charged up state electricity in axe mode, electric effect on charged shield with shield thrust/condensed element slash
efd_0004_c-axe_40_0002.efx = activates with charged shield (at end of element up roundslash). Spark effects when the particles come in contact with the shield?
efd_0004_c-axe_40_0003.efx = those pink particles during element up roundslash
efd_0004_c-axe_41_0000.efx = axe/sword mode morph sparks
efd_0004_c-axe_41_0001.efx = spark effect loop with condensed spinning slash 
efd_0004_c-axe_50_0000.efx = ??? Has energy glows, distortion, etc
efd_0004_c-axe_50_0001.efx = charging electricity during condensed element slash
efd_0004_c-axe_50_0010.efx = overcharged sword loop
efd_0004_c-axe_50_0020.efx = sword mode electricity loop (after condensed element slash)
efd_0004_c-axe_50_0100.efx = shield glow

Charged glow for double slash is not in efd_c-axe. It's a common glow effect used by every weapon type.

=======================================
**Common effects**
[efd_cm]
efd_0004_cm_05_0000.efx = charged glow for every weapon. GS, CB double slash, SnS (charged slash, not perfect rush), bow/HBG charged shots, lance charge swipes, etc
efd_0004_cm_05_0020.efx = charged glow for every weapon, plays at end (after 05_0000)
.....
efd_0004_cm_00_9110.efx = adamant slash (GS), invincible gambit (SA).....
efd_0004_cm_00_9130.efx = counter peak performance sparks (CB)
efd_0004_cm_00_9151.efx = power sheath (GS) and other skills with same pattern

efd_0004_cm_00_9xxx.efx seem to be for wirebugs

**Comment by NSACloud** [comment]
Added.
