### ISSUE TITLE
Palico Equipment ID's

### ISSUE THREAD

**Issue by Dytser** [mhvuze/MonsterHunterRiseModding#11]
Not a complete list, but a fairly decent start since i got down like 80% if not more of the palico equipment stuff (which may even be the same for Palamute, would have to check)

003	Kulu
004	Pukei Pukei
005	Barroth
006	Jouratodus
007	Tobi
008	Anja
009	Rathian
016	Rathalos
017	Diablos
022	Teostra
023	Kushala
026	Bazel
027	D. stench
028	Bone
029	Alloy
101	izuchi
102	Aknosom
103	Tetra
104	Bishaten
105	Somnacanth
106	Magnamalo
107	Goss Harag
108	Almudron
109	Rakna Kadaki
110	Ibushi
111	Narwa
112	Arzuros
113	????
114	Lagombi
115	?????
116	Ludroth
117	Khezu
118	Volvidon
119	???
120 	Barioth
121	Nargacuga
122	Mizutsune
123	Zinogre
124	Tigrex
125	Puppeteer
127	Genie
128	Valstrax
129	Slagtoth
130	???
131	jaggi
132	Altaroth
133	Bnahabra
134	popo S (pig)
135	Rhenoplos
136	Innerwear?
137	Kamura
138	Jelly
139	Weapon only
140	Stealth
141	Acorn
142	Weapon only
143	???
144	???
145	???
146	Magnamalo Amiibo?
147 	Tsukino
148	Weapon only
149	Body only
150	Forest Cat
151	Nine tail cat
152	???
153	???
154	???
...
157	Palamute looking thing

**Comment by NSACloud** [comment]
Added.

**Comment by Dytser** [comment]
You did add it as "Palamute" ID's instead of palico, i have not actually confirmed if it is the same for palamute or only for palico.

Some stuff for sure is only palico related like the 157 given those are DLC's related to palicoes.
Same goes for 151 too.

**Comment by Dytser** [comment]
Ah nice! Thank you NSA!
Yea i thought they may differ to some degree, wasnt sure to what extent.
