### ISSUE TITLE
Weapon effects identification (all weapons, shared)

### ISSUE THREAD

**Issue by MrNiggles** [mhvuze/MonsterHunterRiseModding#13]
Contributed by Yian Konchu#3380 (MrNiggles).

[efd_l-swd]
efd_0004_l-swd_00_0000.efx = ??? Same as Switch Axe
efd_0004_l-swd_00_0001.efx = ??? Same as Switch Axe (activates on blue crit flash zones)
efd_0004_l-swd_00_0005.efx = part of spirit slash red aura
efd_0004_l-swd_00_0010.efx = part of spirit slash red aura
efd_0004_l-swd_00_0011.efx = activates with spirit step slash
efd_0004_l-swd_01_0000.efx = special sheathe flash
efd_0004_l-swd_10_0010.efx = helm breaker
efd_0004_l-swd_99_0000.efx = Zinogre LS effects

The white outline from spirit slash is likely found in the common effects folder

[efd_g-swrd]
efd_0004_g-swd_00_0000.efx = ??? Same as Switch Axe
efd_0004_g-swd_00_0001.efx = ??? Same as Switch Axe (activates on blue crit flash zones)
efd_0004_g-swd_01_0000.efx = ???
efd_0004_g-swd_02_0000.efx = red TCS aura when you land the first hit

most of GS effects are in the common effects folder

[efd_h-bg]
efd_0004_h-bg_10_0000.efx = wyvernheart muzzle
efd_0004_h-bg_10_0001.efx = wyvernsnipe muzzle
efd_0004_h-bg_20_0000.efx = wyvern shot muzzle flame (during the charge, not the explosion)

Note that HBG only uses efd_0004_cm_05_0000.efx for its charge shots, and HBG seem to use many of LBG's weapon effects

[efd_l-bg]
efd_0004_l-bg_00_0000.efx = wyvernblast distortion and smoke 
efd_0004_l-bg_00_0001.efx = ??? Has muzzle flash, explosion, blur
efd_0004_l-bg_00_0002.efx = ??? Has muzzle flash, explosion, blur
efd_0004_l-bg_00_0003.efx = wyvernblast explosion
efd_0004_l-bg_00_0005.efx = ??? Has explosion, fire, blur
efd_0004_l-bg_00_0006.efx = unsure where it's used for LBG. Wyvern ammo explosion (HBG)
efd_0004_l-bg_00_0007.efx = unsure where it's used for LBG. Wyvernsnipe explosion (HBG)
efd_0004_l-bg_00_0008.efx = slicing ammo slashes. Also used by HBG
efd_0004_l-bg_00_0009.efx = cluster and sticky ammo explosion. Also used by HBG
efd_0004_l-bg_01_0000.efx = rocket exhaust from most shots (normal/pierce/status/element/buff/heal/exhaust/tranq). Also used by HBG
efd_0004_l-bg_01_0002.efx = shrapnel ammo bullets. Also used by HBG
efd_0004_l-bg_01_0003.efx = spread ammo bullets. Also used by HBG
efd_0004_l-bg_01_0004.efx = rocket exhaust from cluster and sticky shots. Also used by HBG 
efd_0004_l-bg_01_0005.efx = unsure where it's used for LBG. Wyvernheart bullets (HBG)
efd_0004_l-bg_01_4000.efx = unsure where it's used for LBG. Part of counter shot bullet (HBG)
efd_0004_l-bg_02_0001.efx = sticky/slicing/wyvernsnipe shot when it sticks to the monster. Also used by HBG
efd_0004_l-bg_10_0000.efx = muzzle flash for most shots (normal/pierce/status/element/buff/heal/exhaust/tranq). Also used by HBG
efd_0004_l-bg_10_0001.efx = muzzle flash for spread/shrapnel shots. Also used by HBG
efd_0004_l-bg_10_0002.efx = muzzle flash for sticky/cluster shots. Also used by HBG
efd_0004_l-bg_10_4000.efx = unsure where it's used for LBG. Counter shot muzzle during the charge (HBG)
efd_0004_l-bg_10_4001.efx = unsure where it's used for LBG. Part of counter shot bullet (HBG)
efd_0004_l-bg_10_4010.efx = unsure where it's used for LBG. Counter charger muzzle (HBG)

[efd_hrn]
efd_0004_hrn_00_0000.efx = coloured distortion from regular notes
efd_0004_hrn_00_0010.efx = distortion from performance (R2 on PS4, RT for X360)
efd_0004_hrn_00_4000.efx = distortion from earthshaker hits

musical notes are probably a shared effect. since it's not found in efd_hrn

[efd_ham]
efd_0004_ham_00_0000.efx = ??? Emitter effect (same as gunlance)
efd_0004_ham_01_0000.efx = successful water strike
efd_0004_ham_10_0000.efx = crater from...well....impact crater
efd_0004_ham_99_0000.efx = idle flame effect from death stench hammer
efd_0004_ham_99_0001.efx = charge effect from Zinogre hammer
efd_0004_ham_99_0002.efx = transform effect from Rajang hammer
efd_0004_ham_99_0003.efx = transform effect from Rajang hammer (plays after 002)

[efd_s-swd]
efd_0004_s-swd_02_0000.efx = drill slash hit effect
efd_0004_s-swd_10_0000.efx = red aura from Akuma layered
efd_0004_s-swd_10_0001.efx = ??? has energy glow, probably has to do with Akuma
efd_0004_s-swd_10_0100.efx = windmill with Akuma layered
efd_0004_s-swd_10_0200.efx = metsu shoryugeki and falling bash with Akuma layered

[efd_lan]
efd_0004_lan_00_0000.efx = power guard aura
efd_0004_lan_00_0003.efx = wind effect from cross sweep (after insta block)
efd_0004_lan_01_0000.efx = wind effect from dash attack/shield charge/finishing thrust
efd_0004_lan_01_0001.efx = wind effect from spiral thrust
efd_0004_lan_01_0002.efx = wind effect from anchor rage
efd_0004_lan_10_0000.efx = anchor rage aura

[efd_g-lan]
efd_0004_g-lan_00_0000.efx = ??? Emitter effect (same as hammer)
efd_0004_g-lan_00_0010.efx = reload sparks and smoke
efd_0004_g-lan_01_0000.efx = normal shell explosion (full burst, blast dash/charged shots, aerial shots)
efd_0004_g-lan_01_0001.efx = long shell explosion (full burst, blast dash/charged shots, aerial shots)
efd_0004_g-lan_01_0002.efx = wide shell explosion (full burst, blast dash/charged shots, aerial shots)
efd_0004_g-lan_02_0000.efx = charge shot muzzle torch (during the charge)
efd_0004_g-lan_02_0001.efx = charge shot muzzle torch lvl 2 (wide shells only)
efd_0004_g-lan_04_0000.efx = wyvern fire muzzle torch
efd_0004_g-lan_04_0010.efx = wyvern fire explosion
efd_0004_g-lan_04_0020.efx = wyvern fire cooldown smoke and distortion
efd_0004_g-lan_05_0000.efx = exhaust smoke from wyrmstake shot
efd_0004_g-lan_05_0010.efx = wyrmstake cannon explosion
efd_0004_g-lan_06_0000.efx = wind effect when you get yeeted with blast dash
efd_0004_g-lan_06_0001.efx = exhaust smoke at end of blast dash
efd_0004_g-lan_06_0002.efx = blast dash muzzle torch
efd_0004_g-lan_64_0000.efx = sparks from ground splitter
efd_0004_g-lan_64_0001.efx = muzzle flame loop from ground splitter
efd_0004_g-lan_64_0010.efx = exhaust smoke from hail cutter

[efd_d-bld]
efd_0004_d-bld_01_0000.efx = aura at start of demon mode/feral demon mode
efd_0004_d-bld_01_0001.efx = aura loop and body glow during demon mode/feral demon mode
efd_0004_d-bld_01_0002.efx = burst of fire at start of feral demon mode (does not play in the air)
efd_0004_d-bld_01_0010.efx = aura loop during arch demon mode

[efd_bow]
efd_0004_bow_00_0100.efx = affinity arc shot
efd_0004_bow_00_0200.efx = healing/brace arc shot
efd_0004_bow_00_1000.efx = arc shot smoke
efd_0004_bow_00_1210.efx = dragon piercer arrow sparks/exhaust emission
efd_0004_bow_00_1211.efx = dragon piercer ground sparks at start
efd_0004_bow_00_1212.efx = dragon piercer wind effect
efd_0004_bow_00_1213.efx = dragon piercer arrow wind effect

[efd_i-gla]
efd_0004_i-gla_00_0000.efx = muzzle smoke from aimed kinsect mark shot
efd_0004_i-gla_00_0001.efx = kinsect mark bullet
efd_0004_i-gla_00_0010.efx = kinsect mark smoke on the monster
efd_0004_i-gla_00_0020.efx = kinsect powder
efd_0004_i-gla_00_0030.efx = kinsect powder explosion
efd_0004_i-gla_00_0040.efx = assist kinsect light effect during attacks/charged attack effect from speed kinsect
efd_0004_i-gla_00_0050.efx = circular distortion effect around glaive during kinsect recall/extract
efd_0004_i-gla_00_4000.efx = recall kinsect particles
efd_0004_i-gla_10_0000.efx = muzzle smoke during glaive vault, mid-air evade, jumping advancing slash
efd_0004_i-gla_20_0000.efx = ??? Has smoke and sand effect
efd_0004_i-gla_30_0000.efx = 3 extract buff effect (not the body glow. That's likely efd_0004_cm_05_0000.efx)

[efd-cm]
efd_0004_cm_00_9151.efx = power sheath (GS), fanning maneuver (LBG)
efd_0004_cm_00_9181.efx = ??? Used by LBG
efd_0004_cm_00_9220.efx = serene pose counter (LS), palamute counter (activates with silkbind guard counters like CB counter peak performance)
efd_0004_cm_05_0030.efx = blue aura from foresight slash/iai spirit slash (LS), counter (Lance)
efd_0004_cm_12_0000.efx = mortar reticle, used for cluster bombs (HBG/LBG) and siege weapons like cannons

**Comment by dtlnor** [comment]
I think you may use this ref script to help you identify the effect 
https://puu.sh/IMvnJ/8530ccf48a.zip

**Comment by NSACloud** [comment]
Added.
