### ISSUE TITLE
New Armor ID's

### ISSUE THREAD

**Issue by MinoumimiSenpai** [mhvuze/MonsterHunterRiseModding#14]
Here's the ID for the new Armors
Might want to verify the new DlC parts "269-285-286-287"
except 288 the rest of them lack in details.. 
which made it very hard to pinpoint and even then.. 
until i recolor test them 1 by 1 i cannot say it's 100%

pl269  =  Reverent Wrap
pl270  =  Felyne Stealth Hood
pl271  =  Kamura Cloak
pl278  =  Origin
pl280  =  Defender
pl285  =  Bow Necklace
pl286  =  Leather Choker
pl287  =  Frilled Choker
pl288  =  Benevolent Bandage
pl289  =  Orion
pl290  =  Gala
pl291  =  Raider
pl293  =  USJ Azure

Also USJ Weapons Are
Bow089
L_Swd090

**Comment by dtlnor** [comment]
I have updated all the weapon id, armor id, item id to 3.9.0 data just now, you may take a look.
