### ISSUE TITLE
NPC Identification

### ISSUE THREAD

**Issue by MrNiggles** [mhvuze/MonsterHunterRiseModding#15]
Contributed by Yian Konchu#3380 (MrNiggles).

natives\STM\npc\mod

npc001_00 = Fugen (Kamura elder)
npc002_00 = Hinoa
npc003_00 = Kagero (Kamura merchant)
npc004_00 = Yomogi (Dango girl)
npc005_00 = Hamon (Kamura village smithy)
npc006_00 = male NPCs wearing Kamura bracers/waist + toolbag (gathering hub smithy, that one dude simping hard to Hinoa, Tsuriki the sailor...)
npc007_00 = felynes wearing Kamura bracers/waist (smithy cats, that one cat snoozing by the docks, training area cats...)
npc008_00 = Senri the mailman
npc009_00 = Hanenaga (that hunter guy who keeps doing ninja poses)
npc010_00 = Komitsu the sweettooth
npc013_00 = cohoot
npc013_01 = cohoot default costume
npc013_02 = cohoot costume "Rugged Fullsuit"
npc013_03 = cohoot costume "Garb of Glad Tidings"
npc013_04 = cohoot costume "Stealth Woof"
npc013_05 = DLC cohoot costume "Out on the Hunt"
npc013_06 = DLC cohoot costume "Fluffy Hood"
npc013_07 = DLC cohoot costume "Summery Sailor"
npc013_08 = DLC cohoot costume "Ace Pilot"
npc013_09 = DLC cohoot costume "Puffy Penguin"
npc013_10 = DLC cohoot costume "Menacing Macaw"
npc013_11 = DLC cohoot costume "Wind-up Cohoot"
npc013_12 = DLC cohoot costume "Li'l Wingdrake"
npc013_13 = DLC cohoot costume "Reindeer Party"
npc013_14 = DLC cohoot costume "Pretty Present"
npc014_00 = male NPCs in Kamura village wearing only Kamura bracers (Senari, Inukai...)
npc016_00 = female NPCs in Kamura village (Wakana, Suzukari, that umbrella merchant...)
npc017_00 = rice ball artist Seihaku
npc018_00 = Kamura gathering hub felynes (Maido, Utemai, etc)
npc031_00 = Kamura village merchant popo
npc037_00 = ??? It's an item model
npc101_00 = Hojo + walking cane
npc102_00 = Minoto with her book + drawing paper
npc103_00 = Utsushi
npc107_00 = Ayame (Kamura gathering hub hunter)
npc110_00 = baby tetsu
npc301_00 = felyne chief Kogarashi (the buddy plaza ninja cat)
npc302_00 = buddy handler Iori
npc303_00 = argosy trader Rondine 
npc305_00 = felynes with Kamura innerwear (like your housekeeper)
npc311_00 = tetranadon training dummy
npc314_00 = felynes without clothes (informant in your house, that one obsessed with fish...)

**Comment by NSACloud** [comment]
Added.
