### ISSUE TITLE
Can I get wiki write access?

### ISSUE THREAD

**Issue by Synthlight** [mhvuze/MonsterHunterRiseModding#17]
I'm planning to write up a tutorial with pics on how to extract things with RETool since so many seem to skip the file list and wind up with hashes or just don't understand what a bat / command arguments are.

If you'd rather not give me the access, I could also try writing it on on the editor wiki and just give you the source for it.
Whatever you prefer.

**Comment by mhvuze** [comment]
Invite sent!
