### ISSUE TITLE
End of stream exception when extracting .17 text file. 

### ISSUE THREAD

**Issue by A2CJB** [mhvuze/MonsterHunterRiseModding#18]
This doesn't happen with all the .17 text files but extracting them with REEngine text tool back into their original format fires an exception 'EndOfStreamException'. The text file that I'm trying to extract/convert is HN_Hunternote_Menu_MR.msg.17. 
![image](https://user-images.githubusercontent.com/47431846/176997756-2dba38d1-523d-4220-b0e9-325e63607580.png)

**Comment by Foldhelmna** [comment]
i have the same kind of error, but it's when i want to open it again after i have changed the base message
also some files such the one you are talking about have 0 ko...

**Comment by A2CJB** [comment]
> 

Yeah. exactly this. I can convert the .17 file into a text file no problem, I then edit it to my liking but when I try and convert it back into .17 format it causes this error and the new file ends up with 0KB of size. So it seems like the file gets corrupted during the conversion process but not all files will do this. Other .17 files work fine.

**Comment by Foldhelmna** [comment]
i wonder if it can be corrupted if you add/delete too many values

**Comment by Foldhelmna** [comment]
did it work ig ?

**Comment by A2CJB** [comment]
No it's still broken but I don't know if it's a problem with the text tool needing to be updated by the author. I can't update it.

**Comment by DavidPires** [comment]
I've found the issue. The problem is when a text file has empty strings, like this:

![Capturar](https://user-images.githubusercontent.com/18236868/181566401-be790c96-d81c-4b88-8fac-c3e22542ffab.JPG)

Writing something in those empty strings and then trying to convert back to msg.17, does not solve the problem.

**Comment by Foldhelmna** [comment]
use this tool instead : https://zenhax.com/viewtopic.php?f=12&t=9352#p42860
at least it works

**Comment by DavidPires** [comment]
> use this tool instead : https://zenhax.com/viewtopic.php?f=12&t=9352#p42860 at least it works

that tool has an adware... not trustworthy

**Comment by Foldhelmna** [comment]
as you want, but it's the only one i found who works, and i didn't have any problem with it.

**Comment by dtlnor** [comment]
try to use this https://github.com/dtlnor/REMSG_Converter
