### ISSUE TITLE
MHR Retool list (Question)

### ISSUE THREAD

**Issue by Kurainu** [mhvuze/MonsterHunterRiseModding#2]
Can you explain to me how you guys got this much files paths for unpacking with RETool?

Things i already tried:
- with the REHook but my emulator always crashed when i injected it.
- I used an Memory Scanner to search for the Strings and only got a handfull of wwise, mesh, tex path strings

I would appreciate if you would share your knowledge with me that im able to learn a bit more how to tackle this kind of Problem

**Comment by mhvuze** [comment]
We use a combined approach of generating strings/extracting string references from the data files in the .pak as well as something similar to REHook, but [specifically developed](https://github.com/mhvuze/Ryujinx/blob/mhrise-hook-shared/ARMeilleure/Translation/MHRiseHooks.cs) for Ryujinx. 

For the former, you can just scan extracted (unnamed) files for file paths.

For the latter, the general idea is you want to find (e.g. via IDA or Ghidra) and hook (e.g. via modifying emulator code or by doing code injection via DLL or similar) the game function that handles the file paths.

**Comment by Kurainu** [comment]
Oh Thanks for sharing it with me!
I look into it and try to make sense out of it how you done it.

I also tried to find some functions that handles the file paths in the source code of Ryujinx but my problem is my lack of time and i didnt know how to efficently search for it. i still must learn how to injected/hook functions properly (i already know the genereal doing).
