### ISSUE TITLE
Some motlist identifications

### ISSUE THREAD

**Issue by MrNiggles** [mhvuze/MonsterHunterRiseModding#24]
Identified by Yian Konchu#3380 (MrNiggles).

**[plc_Emotion_003.motlist]**
_(last 3 digits are mot IDs, so 003_001 = mot ID 1, 003_027 = mot ID 27)_

003_001 = greeting
003_002 = wave start
003_003_loop = wave loop
003_004 = applaud start
003_005_loop = applaud loop
003_006 = good work
003_008 = point
003_010 = call start
003_011_loop = call loop
003_012 = woohoo start
003_013_loop = woohoo loop
003_014 = joy 1 start
003_015_loop = joy 1 loop
003_016 = taunt start
003_017_loop = taunt loop
003_018 = stop stop stop start
003_019_loop = stop stop stop loop
003_020 =  high five
003_022 = refuse
003_024 = apologize
003_026 = show off 1 start
003_027_loop = show off 1 loop
003_028 = show off 1 end
003_029 = show off 2 start
003_030_loop = show off 2 loop
003_031 = show off 2 end
003_032 = oh yeah start
003_033_loop = oh yeah loop
003_040 = shadowbox start
003_041_loop = shadowbox loop
003_042 = shadowbox end
003_043 = crossed arms start
003_044_loop = crossed arms loop
003_045 = crossed arms end
003_051 = remorse start
003_052_loop = remorse loop
003_053 = remorse end
003_055 = for honor start
003_056_loop = for honor loop
003_057 = for honor end
003_058 = spirit fingers start
003_059_loop = spirit fingers loop
003_060 = spirit fingers end
003_061 = spirit fingers end 2 (other side)
003_062 = prance start
003_063_loop = prance loop
003_064 = regret start
003_065_loop = regret loop
003_066 = kneel start
003_067_loop = kneel loop
003_068 = kneel end
003_069 = OMG start
003_070_loop =- OMG loop
003_071 = bow
003_072 = genuflect
003_073_loop = genuflect loop
003_074 = flourish
003_075_loop = flourish loop
003_076 = flourish end
003_077 = shock
003_078 = have fun
003_079_loop = have fun loop
003_080 = have fun end
003_081 = LOL start
003_082_loop = LOL loop
003_083 = LOL end
003_087 = morale boost start
003_088_loop = morale boost loop
003_089 = morale boost end
003_090 = ponder start
003_091_loop = ponder loop
003_092 = ponder end
003_100 = standing to sitting on bench
003_102 = sitting on bench to standing back up 
003_105 = wave end
003_106 = applaud end
003_107 = taunt end
003_108 = OMG end
003_109 = genuflect end
003_110 = warm up start
003_111_loop = warm up loop (hands up in the air)
003_112 = warm up (transition from 111 to 113)
003_113_loop = warm up loop (X arms and bent legs) 
003_114_loop = warm up flex
003_115 = warm up transition (114 to 116)
003_116_loop = warm up potion loop
003_117 = warm up pickaxe
003_118 = warm up pickaxe
003_119 = warm up pickaxe
003_120 = warm up transition (119 to 121)
003_121 = warm up pick up start
003_122_loop = warm up pick up loop
003_123 = warm up bow pull
003_124 = warm up start (climbing left/right motion?)
003_125_loop = warm up loop (climbing left/right motion?)
003_126 = transition from 125 to 127
003_127 = warm up sharpen
003_128 = warm up sharpen
003_129 = warm up hammer
003_130 = warm up hammer
003_131 = warm up hammer
003_132 = warm up transition (131 to 133)
003_133_loop = warm up jumps
003_134 = warm up transition (from 133 to 135)
003_135 = warm up transition (to 136, X arms to standing)
003_136 = warm up end

003_291 to 003_355 = palico/palamute interactions

003_400_Loop ~ 405_Loop = cutsey pose
003_406_Loop ~ 411_Loop = powerful pose
003_412_Loop ~ 417_Loop = location pose
003_418_Loop ~ 423_Loop = group pose
003_424_Loop ~ 429_Loop = brawny pose
003_430_Loop ~ 435_Loop = heroic pose
003_436_Loop ~ 441_Loop = dancing pose

003_442_Loop ~ 447_Loop = GS weapon pose (base game)
003_448_Loop ~ 453_Loop = SnS weapon pose (base game)
003_454_Loop ~ 459_Loop = DB weapon pose (base game)
003_460_Loop ~ 465_Loop = LS weapon pose (base game)
003_466_Loop ~ 471_Loop = hammer weapon pose (base game)
003_472_Loop ~ 477_Loop = HH weapon pose (base game)
003_478_Loop ~ 483_Loop = lance weapon pose (base game)
003_484_Loop ~ 489_Loop = GL weapon pose (base game)
003_490_Loop ~ 495_Loop = SA weapon pose (base game)
003_496_Loop ~ 501_Loop = CB weapon pose (base game)
003_502_Loop ~ 507_Loop = IG weapon pose (base game)
003_508_Loop ~ 513_Loop = bow weapon pose (base game)
003_514_Loop ~ 519_Loop = HBG weapon pose (base game)
003_520_Loop ~ 525_Loop = LBG weapon pose (base game)

003_526_Loop ~ 531_Loop  = cool pose 
003_533_Loop ~ 536_Loop  = cutesy pose 2
003_538_Loop ~ 543_Loop  = noble pose
003_544_Loop ~ 549_Loop  = dancing pose 2 
003_552_Loop ~ 555_Loop  = heroic pose 2

003_556_Loop ~ 558_Loop  = GS weapon pose 2
003_559_Loop ~ 561_Loop  = SnS weapon pose 2
003_562_Loop ~ 564_Loop  = DB weapon pose 2
003_565_Loop ~ 567_Loop  = LS weapon pose 2
003_568_Loop ~ 570_Loop  = hammer weapon pose 2
003_571_Loop ~ 573_Loop  = HH weapon pose 2
003_574_Loop ~ 576_Loop  = lance weapon pose 2 
003_577_Loop ~ 579_Loop  = GL weapon pose 2 
003_580_Loop ~ 582_Loop  = SA weapon pose 2
003_583_Loop ~ 585_Loop  = CB weapon pose 2 
003_586_Loop ~ 588_Loop  = IG weapon pose 2 
003_589_Loop ~ 591_Loop = bow weapon pose 2 
003_592_Loop ~ 594_Loop = HBG weapon pose 2
003_595_Loop ~ 597_Loop = LBG weapon pose 2

===============================================
**[Some other motlists]**

plc_DLCv1_019.motlist = fanfare, High five gestures, Attack poses, hurt poses
plc_DLCv2_020.motlist = ninjutsu, delightful dance gestures, idol poses
plc_DLCv3_021.motlist = blow a kiss gesture, using the wall poses, hide poses 
plc_DLCv4_022.motlist = play possum, traditional dance gestures
plc_DLCv5_023.motlist = mew mew gestures
plc_DLCv6_024.motlist = akuma gestures and poses  
plc_DLCv7_025.motlist = arthur
plc_DLCv8_026.motlist = wirebug poses, arthur (has same motions as DLCv7_025)
plc_DLCv9_027.motlist = kunai poses
plc_DLCv10_028.motlist = hot and cold poses
plc_DLCv11_029.motlist = sitting poses
plc_DLCv12_030.motlist = heart poses
plc_DLCv13_031.motlist = running poses
plc_DLCv14_033.motlist = graceful dance gestures, chase poses
plc_DLCv15_034.motlist = it's over gestures, for the fans gestures, MC poses, delightful poses
plc_DX_018.motlist = base game deluxe gestures and poses (jumping, samurai...)
plc_DXv2_032.motlist = aim gestures, fight poses
plc_Edit_014.motlist = character creation motions (the ones used for testing voices)

**Comment by NSACloud** [comment]
Added.
