### ISSUE TITLE
Sunbreak endemics

### ISSUE THREAD

**Issue by MrNiggles** [mhvuze/MonsterHunterRiseModding#25]
Identified by Yian Konchu#3380 (MrNiggles)

ec050 = regalfin
ec051 = gargolda
ec052 = slicercrab
ec053 = spearsquid
ec054 = thornytoad
ec055 = starburst bug
ec056 = gold/ruby wirebug
ec057 = marionette spider

**Comment by NSACloud** [comment]
Added.
