### ISSUE TITLE
armor id can't see

### ISSUE THREAD

**Issue by Caelume05** [mhvuze/MonsterHunterRiseModding#27]
The wiki page took too long to render.
This wiki page’s content is too large to render on this page.

**Comment by dtlnor** [comment]
now it split into two list
* [Base Armor IDs](https://github.com/mhvuze/MonsterHunterRiseModding/wiki/Base-Armor-IDs)
* [SunBreak Armor IDs](https://github.com/mhvuze/MonsterHunterRiseModding/wiki/SunBreak-Armor-IDs)
