### ISSUE TITLE
Arena Equipment?

### ISSUE THREAD

**Issue by Nekkowe** [mhvuze/MonsterHunterRiseModding#33]
I couldn't find any info on this anywhere - how does the game handle equipment for the arena quests? 

Is it even possible to make custom quests for the Arena? Not just for the arena as a map for a normal quest, but for the arena proper, with specified equipment sets and everything.

**Comment by dtlnor** [comment]
/Quest/Arena/*

new arena quest should be fine, if you edit it properly

**Comment by Nekkowe** [comment]
> /Quest/Arena/*  

Sorry, I don't understand what you mean by that. What is that a path to?
I don't see a path like that in this repo, or its wiki, or the quest editor/loader, or the game files.

> if you edit it properly

How do I have to edit the arena quest to set the equipment? I haven't managed to find any information on that here or elsewhere, so I'm struggling with this.

**Comment by dtlnor** [comment]
if you don't find this file, use 
https://www.nexusmods.com/monsterhunterrise/mods/849
this to unpack.

or the RETool modified for MHR
https://github.com/mhvuze/MonsterHunterRiseModding/raw/main/files/REtool.exe

**Comment by Nekkowe** [comment]
Ah, thank you very much! That clears up one of my misconceptions, I had my hopes up that this would be possible with the existing Quest Loader/Editor mod alone somehow.

**Comment by Nekkowe** [comment]
Ah yup, it's all in here, even the switch skills and decorations and stuff. Thanks again!
![image](https://github.com/user-attachments/assets/e64dc887-0f90-4210-81f0-f48b34d1f9d9)
