### ISSUE TITLE
Stage identification (Village)

### ISSUE THREAD

**Issue by MrNiggles** [mhvuze/MonsterHunterRiseModding#4]
Found by me

**natives\STM\stage\v01**
a00 = steelworks
a01 = your room
a02 = buddy plaza
a03 = gathering hall
a04 = gathering hall smithy area
a05 = training area

**natives\STM\stage\v01\setmodel**
sm811 = foliage
sm812 = rocks, boulders

**natives\STM\stage\v01\setmodel\sm813**
sm813_000 = item box
sm813_001 = buddy totem
sm813_002 = Hinoa's bench
sm813_003 = paper lanterns
sm813_004 = wooden lantern posts (the ones with horns at the top)
sm813_005 = bales of coal? Rocks? You see these near the bridge with the umbrella lady
sm813_006 = bales of rice
sm813_020 = ore trinket
sm813_021 = bombadgy pot trinket
sm813_022 = kamura twins trinket
sm813_023 = machalite ore trinket
sm813_024 = palamute trinket
sm813_025 = lucky felyne trinket
sm813_026 = felyne daruma trinket
sm813_027 = moofa trinket
sm813_028 = golden hojo trinket
sm813_031 = melding pot 
sm813_032 = four hanging paper lanterns on a bamboo post, no idea where this is used
sm813_033 = album frame in your room
sm813_034 = album frame in your room
sm813_035 = album frame in your room
sm813_038 = curtains + wall scrolls in the gathering hub
sm813_040 = lantern (hangs from the top), no idea where this is used
sm813_041 = felyne stool (the one in buddy plaza by Iori) 
sm813_042 = dango cooking props
sm813_043 = dango oven
sm813_044 = cooked dango (flat, flat: electric boogaloo 2, bunny), sits on top of 043
sm813_045 = dango cooking prop lid with leaves, sits on top of 042
sm813_048 = dango shop front (the quest board looking thing behind Kinako and Shiratama)
sm813_049 = dango shop sign (the one hanging on the tree branch)
sm813_052 = your bed (laid out), probably the one used in the first cutscene
sm813_053 = your bed (folded)
sm813_054 = wall scroll (the one in buddy plaza by Iori) 
sm813_055 = huge pile of leaves, no idea where this is used
sm813_056 = rathian wall scroll 
sm813_057 = sealed shrine (buddy plaza)
sm813_058 = gathering hub book (Maido's)
sm813_059 = gathering hub dango shop's cooking lid
sm813_060 = bowl of soup, empty bowls, stacked empty bowls
sm813_061 = quest board
sm813_062 = sonic
sm813_063 = tails
sm813_064 = knuckles
sm813_900 = wooden stairs, no idea where this is used
sm813_901 = wooden crate full of spices? Gunpowder? No idea where this is used
sm813_902 = wooden box with hay wrapping, the ones by the docks in the village (not buddy plaza)
 

**natives\STM\stage\v01\setmodel\sm814**
sm814_001 = raft
sm814_005 = pointy wooden fence (the ones you see around the village)

**Comment by NSACloud** [comment]
Added.
