### ISSUE TITLE
Charge Blade motions (plw_ChargeAxe_100.motlist)

### ISSUE THREAD

**Issue by MrNiggles** [mhvuze/MonsterHunterRiseModding#5]
**Identified by ampo, all credit goes to him**

Note that the numbers here mean the last 3 digits of the mot in the motlist. Example:
001 = plw_ChargeAxe_100_001_Loop
002 = plw_ChargeAxe_100_002
013 = plw_ChargeAxe_100_013

============================================

I compared each clips with the game.
Some of the clips with poor descriptions, like clip 328, 329, might be wrong, and some clips marked as "?" are clips that I couldn't figure out what they are.

001: 검방 idle
017: 도끼 idle

001: sword idle
002: sword draw
003: sword sheath while standing still
004: sword walking
005: sword walking start
006: sword turning left to walking
007: sword turning right to walking
008: sword walking stop
009: sword sheath while walking
010: sword roll forward
011: sword side-step-left
012: sword side-step-right
013: sword rolling back
014: sword rolling to walk forward
015: sword rolling to walk back
017: axe idle
018: axe turning right
019: axe turning back
020: axe turning left
021: axe turning back
022: axe walking start
023: axe walking
024: axe walking stop
025: axe roll forward
026: axe roll left
027: axe roll right
028: axe roll backward
029: axe sheath while walking
065: axe sheath while standing still
071: sword climb
072: sword climb
073: sword climb
074: sword jumping down
075: sword jumping down
076: sword landing
077: sword landing to walking
078: sword landing to walking
079: sword landing
080: sword climb
081: sword climb
082: sword climb
083: axe jumping down
084: axe jumping down
085: axe landing
086: axe landing ~ walking
087: axe landing
088: axe landing
101: sword Weak Slash
102: sword Return Stroke
103: sword Forward Slash
104: sword Charged Double Slash start
105: sword Charged Double Slash charging
106: sword Charged Double Slash success
107: sword Charged Double Slash fail
108: sword Spinning Slash
109: sword Shield Thrust
110: sword Charge success
111: sword Charge fail
112: sword Fade Slash Forward
113: sword Fade Slash Back
114: sword Fade Slash Left
115: sword Fade Slash Right
116: sword Condensed Element Slash start
117: sword Condensed Element Slash charging
118: sword Condensed Element Slash success
119: sword morph slash
120 ~ 121: ?
122: axe hopper cancel start
123: axe hopper cancel 
124: axe hopper cancel end
125: axe dash slam
126: axe atk up
127: axe atk down
128: axe Elemental Discharge I
129: axe Elemental Discharge II
130: AED/SAED start
131: AED
132: AED finish
133: SAED
134: SAED finish
135: axe air attack
136: ?
137 ~ 138: axe air attack
139 ~ 140: ?
153: counter morph slash (sword to axe)
154: counter morph slash (axe to sword)
155: condensed spinning slash charge start
156: condensed spinning slash charge
157: condensed spinning slash attack after charging it
158: morphing advance
159: morphing advance
160: counter peak performance start
161: counter peak performance fail
162: counter peak performance success
163: axe hopper start
164: axe hopper start
165: axe hopper do nothing
166: axe hopper AED
167: axe hopper AED
168: axe hopper SAED
169: axe hopper SAED
300: sword foward slash
301 ~ 302: sword Charged Double Slash
303: axe atk down
304: axe atk down
305: SAED to Spinning Slash
306: elemental discharge
307: counter aed
308: ?
309: ?
310: sword charge slash
311: axe atk down
312: sword morph atk
313: ?
314: ?
315: sword morph atk
316: axe atk down to atk up
317: axe atk up
318: axe atk down
319: axe Elemental Discharge II to morphing slash
320: axe ? to morphing slash
321: sword guard point to SAED
322: axe Elemental Discharge II to SAED
323: axe Elemental Discharge I to Elemental Discharge II 
324: axe Elemental Discharge II
325: axe Elemental Discharge II to atk up
326: axe atk down
327: axe walking to Elemental Discharge
328: axe atk down
329: axe atk down
330: sword ? 
331: axe Elemental Discharge
332: axe ?
333: ?
334: Counter Peak Performance to Condensed Spinning Slash
335: Counter Peak Performance to axe atk down
336: Counter Peak Performance to SAED
337: Counter Peak Performance to Condensed Element Slash
338: axe Morphing Advance to SAED
339: sword charge to elemental discharge
340: sword ?
400: sword flinch backward
401: sword flinch left
402: sword flinch right
403: sword flinch forward
404: sword atk bounce off
405: axe flinch backward
406: axe flinch left
407: axe flinch right
408: axe flinch forward
409: axe atk bounce off
411: sword bubble blight stand still
412: sword bubble blight walk
414: sword bubble blight stop
415: axe bubble blight stand still
416: axe bubble blight to walk
418: axe bubble blight stop
420: sheild pushed little
421: sheild pushed 
422: sheild pushed big
430: sheild up start
431: sheild up
432: sheild up to down
433: sheild up moving
450 ~ 453: sword stand up
454 ~ 455: sword wind pressure recover
456: sword Tremor recover
459 ~ 461: climb
462: sword climb to turing back
463 ~ 466: climb
467: axe ? to turning back
468: axe ? to forward
550 ~ 553: axe stand up
554: axe wind pressure recover
555: axe Roar recover
566: axe Tremor recover
605 axe Sharping start
606: Sharping
607: sword Sharping end
608: sword Sharping start
609: Sharping
610: axe Sharping end
611: Sharping

**Comment by NSACloud** [comment]
Added.
