### ISSUE TITLE
Endemic life identification

### ISSUE THREAD

**Issue by MrNiggles** [mhvuze/MonsterHunterRiseModding#6]
Found by me

**natives\STM\environmentCreature**

ec001 = mountain dew (vigorwasp)
ec002 = battletoads (sleepy, para, blast, etc)
ec004 = lantern bug
ec005 = aurortle
ec006 = clothflame
ec007 = antidote snek
ec008 = big manly wirebug
ec009 = spiribirds
ec010 = dung beetles (snow, mud, etc)
ec011 = ??? 
ec012 = rock lizards (rock, boulder, etc)
ec014 = stinkmink
ec015 = escuregot
ec017 = puppet spider
ec018 = wailnard
ec019 = ???
ec020 = butterflame
ec021 = peepersects
ec022 = golden spiribug
ec023 = giganha
ec024 = lampsquids
ec025 = bullet crab (the ones in desert area)
ec026 = echobat
ec027 = snow faced fox
ec028 = quetzalcobra
ec029 = monk snail
ec030 = registrice
ec031 = hellbill
ec032 = fortune owl
ec033 = felicicrow
ec034 = trap bug
ec035 = brewhare
ec036 = trick toad
ec037 = cutterfly
ec038 = gust crab
ec041 = ring from sonic collab

**Comment by NSACloud** [comment]
Added.
